### ISSUE TITLE
Decode hex packet pane

### ISSUE THREAD

**Issue by tarinnn** [johnbumgarner/pyshark_usage_overview#2]
Hi, 
Thanks for this repository. I followed it to extract packet pane from pcap file, but as you [mentioned](https://stackoverflow.com/questions/64808226/pulling-data-from-pyshark) the results came as hex. I am trying to decode it but nothing seems to work. Do you have any hint on how Wireshark does the decoding and if there is anything in pyshark that can help with the decoding? 

thanks

**Comment by johnbumgarner** [comment]
I just posted some documentation on decoding packets.  Let me if the documentation helps you.
