### ISSUE TITLE
Traceack error for pkt..maybe i wong somethin'?

### ISSUE THREAD

**Issue by Ayanashi** [johnbumgarner/pyshark_usage_overview#4]
_>>> pkt.layers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pkt' is not defined_

**Comment by johnbumgarner** [comment]
Where is the rest of your code?

**Comment by johnbumgarner** [comment]
The code that I requested was never provided, so I’m closing this issue.
